### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by Sphygo** [anonymousthing/ListenMoeClient#19]
I like having the viewer on top all the time, but can there be an overall transparency option? It's not huge and in the way, but I'd still like to see what's underneath the player. Especially in games and when watching videos fullscreen. I can pause the music, but there is still a bix box covering that part of the screen unless I close and re-open it every time.

**Comment by bitnimble** [comment]
I'll look into it.

**Comment by bitnimble** [comment]
Appears like so: ![](https://i.imgur.com/9Eqosh6.png)

I'll make a new release soon with the feature.

**Comment by Sphygo** [comment]
Awesome, thanks!

**Comment by Sphygo** [comment]
Actually, I have two more ideas. What about making it able to snap to the very bottom corners to make it cleaner when using full-screen things that hide the taskbar so you can move it down while in those screens and then easily move it back up to above the taskbar afterward? The second is adding another arrow somewhere that collapses the bar into a box. Basically with the play/pause button and the re-large arrow on it. Smaller, more compact, still retains volume and play/pause function. And maybe the favorite star. Love the program, and thanks for the fast reply.
![button](https://user-images.githubusercontent.com/33641459/32759741-adc57f50-c8b0-11e7-98e3-a96fc96cb41c.png)
Something like this.

**Comment by bitnimble** [comment]
Yep, I can see how that would be good. For the snapping, unfortunately when a "full screen" application is open, it is difficult to detect (since they're not actually full screen, they're just a big window that's _also_ just on top of the taskbar). So the solution is somewhere in the middle, where I just make it snap to _both_ the taskbar and the monitor edge. For your purposes this should be fine, but it just means that there'll be a random "snap" where the taskbar is behind the full screen application, which tbh isn't really much of an issue.

The compact mode idea is good, and I had already planned to do so. It'll come sometime in the future when I redo the UI anyway to add event notifications and song requesting. I'll make a new ticket for these features later and add you to it so you can get the notification when it's done.

**Comment by Sphygo** [comment]
Sounds good. Glad to see you are so actively working on improvements. And yeah, I did just mean adding a second line to snap to all the time, not auto moving to the bottom when a window makes that space vacant. That would be cool, but I thought just have the current snapping locations plus the very bottom of the screen available all the time, and then manually drag it down when a full window opens and drag it back up when it closes.
